/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as EditorialRouteImport } from './routes/editorial'
import { Route as NoticiasDoDiaRouteImport } from './routes/noticias-do-dia'
import { Route as NoticiasRecentesRouteImport } from './routes/noticias-recentes'
import { Route as EditoriaSectionRouteImport } from './routes/editoria.$section'
import { Route as NoticiaSlugRouteImport } from './routes/noticia.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialRoute = EditorialRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasDoDiaRoute = NoticiasDoDiaRouteImport.update({
  id: '/noticias-do-dia',
  path: '/noticias-do-dia',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRecentesRoute = NoticiasRecentesRouteImport.update({
  id: '/noticias-recentes',
  path: '/noticias-recentes',
  getParentRoute: () => rootRouteImport,
} as any)
const EditoriaSectionRoute = EditoriaSectionRouteImport.update({
  id: '/editoria/$section',
  path: '/editoria/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiaSlugRoute = NoticiaSlugRouteImport.update({
  id: '/noticia/$slug',
  path: '/noticia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/editorial': typeof EditorialRoute
  '/noticias-do-dia': typeof NoticiasDoDiaRoute
  '/noticias-recentes': typeof NoticiasRecentesRoute
  '/editoria/$section': typeof EditoriaSectionRoute
  '/noticia/$slug': typeof NoticiaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/editorial': typeof EditorialRoute
  '/noticias-do-dia': typeof NoticiasDoDiaRoute
  '/noticias-recentes': typeof NoticiasRecentesRoute
  '/editoria/$section': typeof EditoriaSectionRoute
  '/noticia/$slug': typeof NoticiaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/editorial': typeof EditorialRoute
  '/noticias-do-dia': typeof NoticiasDoDiaRoute
  '/noticias-recentes': typeof NoticiasRecentesRoute
  '/editoria/$section': typeof EditoriaSectionRoute
  '/noticia/$slug': typeof NoticiaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/busca'
    | '/editorial'
    | '/noticias-do-dia'
    | '/noticias-recentes'
    | '/editoria/$section'
    | '/noticia/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/busca'
    | '/editorial'
    | '/noticias-do-dia'
    | '/noticias-recentes'
    | '/editoria/$section'
    | '/noticia/$slug'
  id:
    | '__root__'
    | '/'
    | '/busca'
    | '/editorial'
    | '/noticias-do-dia'
    | '/noticias-recentes'
    | '/editoria/$section'
    | '/noticia/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscaRoute: typeof BuscaRoute
  EditorialRoute: typeof EditorialRoute
  NoticiasDoDiaRoute: typeof NoticiasDoDiaRoute
  NoticiasRecentesRoute: typeof NoticiasRecentesRoute
  EditoriaSectionRoute: typeof EditoriaSectionRoute
  NoticiaSlugRoute: typeof NoticiaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial': {
      id: '/editorial'
      path: '/editorial'
      fullPath: '/editorial'
      preLoaderRoute: typeof EditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias-do-dia': {
      id: '/noticias-do-dia'
      path: '/noticias-do-dia'
      fullPath: '/noticias-do-dia'
      preLoaderRoute: typeof NoticiasDoDiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias-recentes': {
      id: '/noticias-recentes'
      path: '/noticias-recentes'
      fullPath: '/noticias-recentes'
      preLoaderRoute: typeof NoticiasRecentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editoria/$section': {
      id: '/editoria/$section'
      path: '/editoria/$section'
      fullPath: '/editoria/$section'
      preLoaderRoute: typeof EditoriaSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticia/$slug': {
      id: '/noticia/$slug'
      path: '/noticia/$slug'
      fullPath: '/noticia/$slug'
      preLoaderRoute: typeof NoticiaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscaRoute: BuscaRoute,
  EditorialRoute: EditorialRoute,
  NoticiasDoDiaRoute: NoticiasDoDiaRoute,
  NoticiasRecentesRoute: NoticiasRecentesRoute,
  EditoriaSectionRoute: EditoriaSectionRoute,
  NoticiaSlugRoute: NoticiaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
