/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as NoticiasDoDiaRouteImport } from './routes/noticias-do-dia'
import { Route as NoticiasRecentesRouteImport } from './routes/noticias-recentes'
import { Route as EditoriaSectionRouteImport } from './routes/editoria.$section'
import { Route as EditorialIndexRouteImport } from './routes/editorial.index'
import { Route as EditorialConfirmarEmailRouteImport } from './routes/editorial.confirmar-email'
import { Route as EditorialCriarContaRouteImport } from './routes/editorial.criar-conta'
import { Route as EditorialEsqueciSenhaRouteImport } from './routes/editorial.esqueci-senha'
import { Route as EditorialPerfilRouteImport } from './routes/editorial.perfil'
import { Route as EditorialRedacaoRouteImport } from './routes/editorial.redacao'
import { Route as EditorialRedefinirSenhaRouteImport } from './routes/editorial.redefinir-senha'
import { Route as EditorialSegurancaRouteImport } from './routes/editorial.seguranca'
import { Route as EditorialUsuariosRouteImport } from './routes/editorial.usuarios'
import { Route as NoticiaSlugRouteImport } from './routes/noticia.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasDoDiaRoute = NoticiasDoDiaRouteImport.update({
  id: '/noticias-do-dia',
  path: '/noticias-do-dia',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRecentesRoute = NoticiasRecentesRouteImport.update({
  id: '/noticias-recentes',
  path: '/noticias-recentes',
  getParentRoute: () => rootRouteImport,
} as any)
const EditoriaSectionRoute = EditoriaSectionRouteImport.update({
  id: '/editoria/$section',
  path: '/editoria/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialIndexRoute = EditorialIndexRouteImport.update({
  id: '/editorial/',
  path: '/editorial/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialConfirmarEmailRoute = EditorialConfirmarEmailRouteImport.update({
  id: '/editorial/confirmar-email',
  path: '/editorial/confirmar-email',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialCriarContaRoute = EditorialCriarContaRouteImport.update({
  id: '/editorial/criar-conta',
  path: '/editorial/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialEsqueciSenhaRoute = EditorialEsqueciSenhaRouteImport.update({
  id: '/editorial/esqueci-senha',
  path: '/editorial/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPerfilRoute = EditorialPerfilRouteImport.update({
  id: '/editorial/perfil',
  path: '/editorial/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialRedacaoRoute = EditorialRedacaoRouteImport.update({
  id: '/editorial/redacao',
  path: '/editorial/redacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialRedefinirSenhaRoute = EditorialRedefinirSenhaRouteImport.update({
  id: '/editorial/redefinir-senha',
  path: '/editorial/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialSegurancaRoute = EditorialSegurancaRouteImport.update({
  id: '/editorial/seguranca',
  path: '/editorial/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialUsuariosRoute = EditorialUsuariosRouteImport.update({
  id: '/editorial/usuarios',
  path: '/editorial/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiaSlugRoute = NoticiaSlugRouteImport.update({
  id: '/noticia/$slug',
  path: '/noticia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/noticias-do-dia': typeof NoticiasDoDiaRoute
  '/noticias-recentes': typeof NoticiasRecentesRoute
  '/editoria/$section': typeof EditoriaSectionRoute
  '/editorial/confirmar-email': typeof EditorialConfirmarEmailRoute
  '/editorial/criar-conta': typeof EditorialCriarContaRoute
  '/editorial/esqueci-senha': typeof EditorialEsqueciSenhaRoute
  '/editorial/perfil': typeof EditorialPerfilRoute
  '/editorial/redacao': typeof EditorialRedacaoRoute
  '/editorial/redefinir-senha': typeof EditorialRedefinirSenhaRoute
  '/editorial/seguranca': typeof EditorialSegurancaRoute
  '/editorial/usuarios': typeof EditorialUsuariosRoute
  '/noticia/$slug': typeof NoticiaSlugRoute
  '/editorial/': typeof EditorialIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/noticias-do-dia': typeof NoticiasDoDiaRoute
  '/noticias-recentes': typeof NoticiasRecentesRoute
  '/editoria/$section': typeof EditoriaSectionRoute
  '/editorial/confirmar-email': typeof EditorialConfirmarEmailRoute
  '/editorial/criar-conta': typeof EditorialCriarContaRoute
  '/editorial/esqueci-senha': typeof EditorialEsqueciSenhaRoute
  '/editorial/perfil': typeof EditorialPerfilRoute
  '/editorial/redacao': typeof EditorialRedacaoRoute
  '/editorial/redefinir-senha': typeof EditorialRedefinirSenhaRoute
  '/editorial/seguranca': typeof EditorialSegurancaRoute
  '/editorial/usuarios': typeof EditorialUsuariosRoute
  '/noticia/$slug': typeof NoticiaSlugRoute
  '/editorial': typeof EditorialIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/noticias-do-dia': typeof NoticiasDoDiaRoute
  '/noticias-recentes': typeof NoticiasRecentesRoute
  '/editoria/$section': typeof EditoriaSectionRoute
  '/editorial/confirmar-email': typeof EditorialConfirmarEmailRoute
  '/editorial/criar-conta': typeof EditorialCriarContaRoute
  '/editorial/esqueci-senha': typeof EditorialEsqueciSenhaRoute
  '/editorial/perfil': typeof EditorialPerfilRoute
  '/editorial/redacao': typeof EditorialRedacaoRoute
  '/editorial/redefinir-senha': typeof EditorialRedefinirSenhaRoute
  '/editorial/seguranca': typeof EditorialSegurancaRoute
  '/editorial/usuarios': typeof EditorialUsuariosRoute
  '/noticia/$slug': typeof NoticiaSlugRoute
  '/editorial/': typeof EditorialIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/busca'
    | '/noticias-do-dia'
    | '/noticias-recentes'
    | '/editoria/$section'
    | '/editorial/confirmar-email'
    | '/editorial/criar-conta'
    | '/editorial/esqueci-senha'
    | '/editorial/perfil'
    | '/editorial/redacao'
    | '/editorial/redefinir-senha'
    | '/editorial/seguranca'
    | '/editorial/usuarios'
    | '/noticia/$slug'
    | '/editorial/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/busca'
    | '/noticias-do-dia'
    | '/noticias-recentes'
    | '/editoria/$section'
    | '/editorial/confirmar-email'
    | '/editorial/criar-conta'
    | '/editorial/esqueci-senha'
    | '/editorial/perfil'
    | '/editorial/redacao'
    | '/editorial/redefinir-senha'
    | '/editorial/seguranca'
    | '/editorial/usuarios'
    | '/noticia/$slug'
    | '/editorial'
  id:
    | '__root__'
    | '/'
    | '/busca'
    | '/noticias-do-dia'
    | '/noticias-recentes'
    | '/editoria/$section'
    | '/editorial/confirmar-email'
    | '/editorial/criar-conta'
    | '/editorial/esqueci-senha'
    | '/editorial/perfil'
    | '/editorial/redacao'
    | '/editorial/redefinir-senha'
    | '/editorial/seguranca'
    | '/editorial/usuarios'
    | '/noticia/$slug'
    | '/editorial/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscaRoute: typeof BuscaRoute
  NoticiasDoDiaRoute: typeof NoticiasDoDiaRoute
  NoticiasRecentesRoute: typeof NoticiasRecentesRoute
  EditoriaSectionRoute: typeof EditoriaSectionRoute
  EditorialConfirmarEmailRoute: typeof EditorialConfirmarEmailRoute
  EditorialCriarContaRoute: typeof EditorialCriarContaRoute
  EditorialEsqueciSenhaRoute: typeof EditorialEsqueciSenhaRoute
  EditorialPerfilRoute: typeof EditorialPerfilRoute
  EditorialRedacaoRoute: typeof EditorialRedacaoRoute
  EditorialRedefinirSenhaRoute: typeof EditorialRedefinirSenhaRoute
  EditorialSegurancaRoute: typeof EditorialSegurancaRoute
  EditorialUsuariosRoute: typeof EditorialUsuariosRoute
  NoticiaSlugRoute: typeof NoticiaSlugRoute
  EditorialIndexRoute: typeof EditorialIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias-do-dia': {
      id: '/noticias-do-dia'
      path: '/noticias-do-dia'
      fullPath: '/noticias-do-dia'
      preLoaderRoute: typeof NoticiasDoDiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias-recentes': {
      id: '/noticias-recentes'
      path: '/noticias-recentes'
      fullPath: '/noticias-recentes'
      preLoaderRoute: typeof NoticiasRecentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editoria/$section': {
      id: '/editoria/$section'
      path: '/editoria/$section'
      fullPath: '/editoria/$section'
      preLoaderRoute: typeof EditoriaSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/': {
      id: '/editorial/'
      path: '/editorial'
      fullPath: '/editorial/'
      preLoaderRoute: typeof EditorialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/confirmar-email': {
      id: '/editorial/confirmar-email'
      path: '/editorial/confirmar-email'
      fullPath: '/editorial/confirmar-email'
      preLoaderRoute: typeof EditorialConfirmarEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/criar-conta': {
      id: '/editorial/criar-conta'
      path: '/editorial/criar-conta'
      fullPath: '/editorial/criar-conta'
      preLoaderRoute: typeof EditorialCriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/esqueci-senha': {
      id: '/editorial/esqueci-senha'
      path: '/editorial/esqueci-senha'
      fullPath: '/editorial/esqueci-senha'
      preLoaderRoute: typeof EditorialEsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/perfil': {
      id: '/editorial/perfil'
      path: '/editorial/perfil'
      fullPath: '/editorial/perfil'
      preLoaderRoute: typeof EditorialPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/redacao': {
      id: '/editorial/redacao'
      path: '/editorial/redacao'
      fullPath: '/editorial/redacao'
      preLoaderRoute: typeof EditorialRedacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/redefinir-senha': {
      id: '/editorial/redefinir-senha'
      path: '/editorial/redefinir-senha'
      fullPath: '/editorial/redefinir-senha'
      preLoaderRoute: typeof EditorialRedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/seguranca': {
      id: '/editorial/seguranca'
      path: '/editorial/seguranca'
      fullPath: '/editorial/seguranca'
      preLoaderRoute: typeof EditorialSegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/usuarios': {
      id: '/editorial/usuarios'
      path: '/editorial/usuarios'
      fullPath: '/editorial/usuarios'
      preLoaderRoute: typeof EditorialUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticia/$slug': {
      id: '/noticia/$slug'
      path: '/noticia/$slug'
      fullPath: '/noticia/$slug'
      preLoaderRoute: typeof NoticiaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscaRoute: BuscaRoute,
  NoticiasDoDiaRoute: NoticiasDoDiaRoute,
  NoticiasRecentesRoute: NoticiasRecentesRoute,
  EditoriaSectionRoute: EditoriaSectionRoute,
  EditorialConfirmarEmailRoute: EditorialConfirmarEmailRoute,
  EditorialCriarContaRoute: EditorialCriarContaRoute,
  EditorialEsqueciSenhaRoute: EditorialEsqueciSenhaRoute,
  EditorialPerfilRoute: EditorialPerfilRoute,
  EditorialRedacaoRoute: EditorialRedacaoRoute,
  EditorialRedefinirSenhaRoute: EditorialRedefinirSenhaRoute,
  EditorialSegurancaRoute: EditorialSegurancaRoute,
  EditorialUsuariosRoute: EditorialUsuariosRoute,
  NoticiaSlugRoute: NoticiaSlugRoute,
  EditorialIndexRoute: EditorialIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
